
[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = false
	enableBerryTheme = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true

